FROM golang:1.13.11-buster

# designate the working directory within the container
WORKDIR /go/src/github.com/damilarelana/goSystemDesign
COPY . .

# Install dependencies
RUN go get -v ./...
RUN go install -v ./...

# Entrypoint
ENTRYPOINT ["go", "run", "./accountService/main.go"]

# Expose the default port
EXPOSE 8081